# A sample Gemfile
source "https://rubygems.org"

gem "sinatra"
gem "sinatra-contrib"
gem "memcache-client"
gem "foreman"
gem "unicorn"
gem "mysql2"
gem 'mysql2-cs-bind'
gem "rack-flash3"
gem "rack-lineprof"
gem "rack-mini-profiler"
gem "flamegraph"
gem "stackprof"
gem "pry-byebug"
gem "pry-doc"
